const CryptoActionTypes = {
  FETCH_START: "FETCH_START",
  BITCOIN_START: "BITCOIN_START",
  BITCOIN_SUCCESS: "BITCOIN_SUCCESS",
  BITCOIN_ERROR: "BITCOIN_SUCCESS",
  ENUMERUM_START: "ENUMERUM_START",
  ENUMERUM_SUCCESS: "ENUMERUM_SUCCESS",
  ENUMERUM_ERROR: "ENUMERUM_ERROR",
  EOS_START: "EOS_START",
  EOS_SUCCESS: "EOS_SUCCESS",
  EOS_ERROR: "EOS_ERROR",
  GET_DATE: "GET_DATE",
};

export default CryptoActionTypes;
